### ISSUE TITLE
Failed to activate the linter package

### ISSUE THREAD

**Issue by awatts** [AtomLinter/linter-gjslint#2]
[Enter steps to reproduce below:]
1. Run `atom filename.coffee`
2. Atom opens with the error.

gjslint is in /usr/local/bin/ which is on my process.env.PATH

Looks like the problem is lines 32 and 33 of linter-gjslint.coffee

``` coffeescript
ignoreList = atom.config.get 'linter-gjslint.gjslintIgnoreList'
      @cmd += " --disable " + ignoreList.join()
```

On my computer at least, `atom.config.get 'linter-gjslint.gjslintIgnoreList'` returns `undefined`, which obviously doesn't have a `.join()` method.

**Atom Version**: 0.188.0
**System**: Mac OS X 10.9.5
**Thrown From**: [linter-gjslint](https://github.com/AtomLinter/linter-gjslint) package, v0.0.4
### Stack Trace

Failed to activate the linter package

```
At Cannot read property 'join' of undefined

TypeError: Cannot read property 'join' of undefined
  at /hlpUsers/awatts/.atom/packages/linter-gjslint/lib/linter-gjslint.coffee:33:41
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:612:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:126:21)
  at new LinterGjslint (/hlpUsers/awatts/.atom/packages/linter-gjslint/lib/linter-gjslint.coffee:31:17)
  at LinterView.initLinters (/hlpUsers/awatts/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/hlpUsers/awatts/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /hlpUsers/awatts/.atom/packages/linter/lib/init.coffee:88:24
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:282:9)
  at LinterInitializer.activate (/hlpUsers/awatts/.atom/packages/linter/lib/init.coffee:85:39)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:461:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:445:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:343:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:440:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:423:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app/src/atom.js:625:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:51:25)

```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
atom-color-highlight, v3.0.8
atom-jinja2, v0.5.0
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-haxe, v0.2.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-plus-async, v0.22.0
autocomplete-snippets, v1.2.0
coffee-compile, v0.11.0
editorconfig, v0.3.3
emmet, v2.3.4
file-icons, v1.5.2
git-log, v0.3.0
highlight-selected, v0.9.1
language-actionscript3, v0.2.0
language-latex, v0.4.1
language-liquid, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.2.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-js-yaml, v1.0.0
linter-jshint, v0.1.0
linter-pep257, v0.2.0
linter-pylint, v0.2.1
linter-rubocop, v0.2.2
linter-scalac, v0.3.3
linter-scss-lint, v0.0.14
minimap, v4.6.0
minimap-git-diff, v4.1.2
minimap-highlight-selected, v4.2.0
project-manager, v1.15.5
save-session, v0.12.3
symbols-tree-view, v0.8.3

# Dev
No dev packages
```

**Comment by kolomiichenko** [comment]
Hi, for begin you can add string `'gjslintIgnoreList:' []` into config.cson (look example: https://github.com/AtomLinter/linter-gjslint/blob/master/README.md#settings)
Sorry, it's my fail in last commit, I promise fixed as soon as possible

**Comment by awatts** [comment]
Yup. I did and that before I even submitted the bug and it fixed it. Just wanted to let you know it could happen to other people, so you should probably check that 'linter-gjslint.gjslintIgnoreList' exists and set it to [] if not. Cheers.

**Comment by kolomiichenko** [comment]
Fixed. Waiting for confirmation pull request https://github.com/AtomLinter/linter-gjslint/pull/3

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/AtomLinter/linter-gjslint/pull/3
