### ISSUE TITLE
gflags.UnrecognizedFlagError: Unknown command line flag 'quiet'

### ISSUE THREAD

**Issue by wil93** [AtomLinter/linter-gjslint#26]
When I try to use this plugin I get this error:

```
Error: Traceback (most recent call last):
  File "/usr/bin/gjslint", line 9, in <module>
    load_entry_point('closure-linter==2.3.13', 'console_scripts', 'gjslint')()
  File "/usr/lib/python2.7/site-packages/closure_linter/gjslint.py", line 236, in main
    argv = flags.FLAGS(sys.argv)
  File "/usr/lib/python2.7/site-packages/gflags.py", line 1319, in __call__
    raise UnrecognizedFlagError(opt, value)
gflags.UnrecognizedFlagError: Unknown command line flag 'quiet'
    at parameters.exit (/home/wil93/.atom/packages/linter-gjslint/node_modules/atom-linter/lib/helpers.js:74:20)
    at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
    at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

I have `closure-linter` installed (2.3.13), and I get a similar error if I run `gjslint --quiet filename.js`, so it seems that `--quiet` is just not a correct flag.

**Comment by artoale** [comment]
Hi! Can you try installing latest closure-linter with `pip install https://closure-linter.googlecode.com/svn/trunk/` as per the [official docs](https://developers.google.com/closure/utilities/docs/linter_howto#install-closure-linter) and see if it works? Latest version should be `2.3.13`

**Comment by wil93** [comment]
Yes, it works that way, however I did have `2.3.13` already. The svn version you cited is actually `2.3.17`.

So, the main issue is that the `closure-linter` published on pypi is out of date. I reported it here: google/closure-linter#97.

Closing, thanks :smile:

**Comment by artoale** [comment]
Yeah, sorry, it was a typo on my end - I meant `2.1.17`. Thanks!
