### ISSUE TITLE
Exception with Atom 0.189.0

### ISSUE THREAD

**Issue by prassie** [AtomLinter/linter-gjslint#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [linter-gjslint](https://github.com/AtomLinter/linter-gjslint) package, v0.0.4
### Stack Trace

Uncaught TypeError: Cannot read property 'join' of undefined

```
At C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:128

TypeError: Cannot read property 'join' of undefined
  at C:\Users\prasannar\.atom\packages\linter-gjslint\lib\linter-gjslint.coffee:33:41
  at Config.module.exports.Config.observeKeyPath (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\config.js:612:7)
  at Config.module.exports.Config.observe (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\config.js:126:21)
  at new LinterGjslint (C:\Users\prasannar\.atom\packages\linter-gjslint\lib\linter-gjslint.coffee:31:17)
  at LinterView.initLinters (C:\Users\prasannar\.atom\packages\linter\lib\linter-view.coffee:51:27)
  at new LinterView (C:\Users\prasannar\.atom\packages\linter\lib\linter-view.coffee:33:6)
  at C:\Users\prasannar\.atom\packages\linter\lib\init.coffee:88:24
  at C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\workspace.js:287:16
  at C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\workspace.js:344:18
  at Emitter.module.exports.Emitter.emit (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\pane-container.js:375:27)
  at C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\pane-container.js:362:26
  at Emitter.module.exports.Emitter.emit (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\pane.js:363:20)
  at Pane.module.exports.Pane.activateItem (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\pane.js:336:14)
  at C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\src\workspace.js:532:16
  at _fulfilled (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:756:13)
  at C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:564:44
  at flush (C:\Users\prasannar\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:357:13)

```
### Commands

```
     -30:36.2 fuzzy-finder:toggle-file-finder (div.settings-view.pane-item)
  2x -30:29.2 core:move-down (atom-text-editor.editor.mini)
     -30:27.9 editor:move-to-first-character-of-line (atom-text-editor.editor.mini)
  2x -30:27.5 core:move-right (atom-text-editor.editor.mini)
     -30:26.9 core:delete (atom-text-editor.editor.mini)
     -30:26.3 core:move-right (atom-text-editor.editor.mini)
     -30:24.8 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "hex",
      "js-refactor",
      "local-server",
      "vertical-align",
      "vim-mode",
      "zentabs",
      "scope-inspector",
      "regex-railroad-diagram",
      "refactor",
      "project-colorize",
      "pomodoro",
      "neon-selection",
      "mobile-preview",
      "Zen",
      "block-travel",
      "git-difftool",
      "angularjs",
      "merge-conflicts",
      "language-objective-c",
      "archive-view",
      "background-tips",
      "dev-live-reload",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-go",
      "language-java",
      "language-mustache",
      "language-make",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-toml",
      "open-on-github",
      "package-generator",
      "welcome"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.8.0
column-select, v0.2.0
highlight-selected, v0.9.1
linter, v0.12.0
linter-csslint, v0.0.11
linter-jscs, v1.9.0
linter-jshint, v0.1.0
linter-jsonlint, v0.1.2
linter-less, v0.3.1
linter-scss-lint, v0.0.14
open-recent, v2.2.0
quick-jump, v0.0.4
word-jumper, v0.2.0

# Dev
No dev packages
```

**Comment by kolomiichenko** [comment]
https://github.com/AtomLinter/linter-gjslint/issues/2#issuecomment-86188002

**Comment by anthonyraymond** [comment]
#6 Should fix the issue

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/AtomLinter/linter-gjslint/pull/3
