### ISSUE TITLE
Error: spawn gjslint ENOENT

### ISSUE THREAD

**Issue by pleabargain** [AtomLinter/linter-gjslint#63]
installed
on reopening atom 1.14.2
I got this err:
```
Error: spawn gjslint ENOENT
File 0Project 0No Issues~/Documents/fcc challenges/forEachfromJSON.js1:1
LFUTF-8JavaScript
Error: spawn gjslint ENOENT
Error: spawn gjslint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

gjslint does not show up in the dropdown Packages and when I ran clear tabs the error message popped up again:
```
Error: spawn gjslint ENOENT
Error: spawn gjslint ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Arcanemagus** [comment]
`gjslint` is an external utility that you need to install ([site](https://developers.google.com/closure/utilities/)).

I would recommend looking into moving to ESLint though as `gjslint` has been deprecated and is no longer being worked on.

**Comment by pleabargain** [comment]
@Arcanemagus many thanks!
