### ISSUE TITLE
Cannot read property 'join' of undefined

### ISSUE THREAD

**Issue by ThinkingBeing** [AtomLinter/linter-gjslint#7]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [linter-gjslint](https://github.com/AtomLinter/linter-gjslint) package, v0.0.4
### Stack Trace

Failed to activate the linter package

```
At Cannot read property 'join' of undefined

TypeError: Cannot read property 'join' of undefined
  at /Users/ligf/.atom/packages/linter-gjslint/lib/linter-gjslint.coffee:33:41
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:555:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:135:21)
  at new LinterGjslint (/Users/ligf/.atom/packages/linter-gjslint/lib/linter-gjslint.coffee:31:17)
  at LinterView.initLinters (/Users/ligf/.atom/packages/linter/lib/linter-view.coffee:51:27)
  at new LinterView (/Users/ligf/.atom/packages/linter/lib/linter-view.coffee:33:6)
  at /Users/ligf/.atom/packages/linter/lib/init.coffee:103:24
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at LinterInitializer.activate (/Users/ligf/.atom/packages/linter/lib/init.coffee:100:39)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:242:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:223:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:215:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:623:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:38:7)

```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "seti-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus, v2.16.3
docblockr, v0.7.1
go-plus, v3.3.10
highlight-line, v0.10.2
highlight-selected, v0.9.2
language-todo, v0.21.0
linter, v0.12.2
minimap, v4.8.0
project-manager, v1.15.5
script, v2.23.0
seti-ui, v0.7.1
sync-settings, v0.2.2

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/AtomLinter/linter-gjslint/pull/3
